/**
 * 歌曲数据 & 配置常量
 * 仅包含"动画中出现的完整演出/插入曲/OP/ED"。
 */

// ============================================================
// 歌曲数据
// ============================================================
const songsData = [
  // S1
  {
    id: 101,
    title: "Don't be afraid!",
    trans: "别害怕！",
    band: "Glitter*Green",
    season: "S1",
    ep: "第1–2话",
    type: "Insert",
  },
  {
    id: 102,
    title: "ときめきエクスペリエンス！",
    trans: "心跳体验",
    band: "Poppin'Party",
    season: "S1",
    ep: "OP",
    type: "OP",
  },
  {
    id: 103,
    title: "キラキラだとか夢だとか ～Sing Girls～",
    trans: "无论闪耀还是梦想~歌之少女~",
    band: "Poppin'Party",
    season: "S1",
    ep: "常规 ED",
    type: "ED",
  },
  {
    id: 104,
    title: "きらきら星 ～初めてのステージVer.～",
    trans: "小星星～初次舞台版～",
    band: "Poppin'Party",
    season: "S1",
    ep: "第3–4话",
    type: "Insert",
  },
  {
    id: 105,
    title: "私の心はチョココロネ",
    trans: "我的心是巧克力螺",
    band: "Poppin'Party",
    season: "S1",
    ep: "第5话",
    type: "Insert",
  },
  {
    id: 106,
    title: "STAR BEAT! ～ホシノコドウ～",
    trans: "STAR BEAT!~星之鼓动~",
    band: "Poppin'Party",
    season: "S1",
    ep: "第8话",
    type: "Insert",
  },
  {
    id: 107,
    title: "前へススメ！",
    trans: "前进吧！",
    band: "Poppin'Party",
    season: "S1",
    ep: "第9、11、12话",
    type: "Insert",
  },
  {
    id: 108,
    title: "Glee! Glee! Glee!",
    trans: "欢呼吧！",
    band: "Glitter*Green",
    season: "S1",
    ep: "第13话",
    type: "Insert",
  },
  {
    id: 109,
    title: "Be shine, shining!!",
    trans: "闪耀吧，光芒！",
    band: "CHiSPA",
    season: "S1",
    ep: "第13话",
    type: "Insert",
  },
  {
    id: 110,
    title: "夢みるSunflower",
    trans: "怀有梦想的向日葵",
    band: "Poppin'Party",
    season: "S1",
    ep: "第13话",
    type: "Insert",
  },
  {
    id: 111,
    title: "八月のif",
    trans: "八月的 if",
    band: "Poppin'Party",
    season: "S1",
    ep: "OVA",
    type: "Insert",
  },
  {
    id: 112,
    title: "熱色スターマイン",
    trans: "热色Star Mine",
    band: "Roselia",
    season: "S1",
    ep: "OVA",
    type: "ED",
  },
  {
    id: 113,
    title: "Don't be afraid!",
    trans: "别害怕！",
    band: "Glitter*Green",
    season: "S1",
    ep: "第1话",
    type: "ED",
  },
  // S2
  {
    id: 201,
    title: "キズナミュージック♪",
    trans: "友谊的华丽乐章♪",
    band: "Poppin'Party",
    season: "S2",
    ep: "第1、3–9、12话",
    type: "OP",
  },
  {
    id: 202,
    title: "BRAVE JEWEL",
    trans: "勇气宝石",
    band: "Roselia",
    season: "S2",
    ep: "第2、10–11话",
    type: "OP",
  },
  {
    id: 203,
    title: "Jumpin'",
    trans: "跃动吧！",
    band: "Poppin'Party",
    season: "S2",
    ep: "第3–8、11–12话",
    type: "ED",
  },
  {
    id: 204,
    title: "Safe and Sound",
    trans: "安稳与守护",
    band: "Roselia",
    season: "S2",
    ep: "第2、9–10话",
    type: "ED",
  },
  {
    id: 205,
    title: "キズナミュージック♪",
    trans: "友谊的华丽乐章♪ 特别版",
    band: "Poppin'Party",
    season: "S2",
    ep: "第13话",
    type: "ED",
  },
  {
    id: 206,
    title: "しゅわりん☆どり～みん",
    trans: "气泡飞舞☆如梦幻",
    band: "Pastel*Palettes",
    season: "S2",
    ep: "第1、13话",
    type: "Insert",
  },
  {
    id: 207,
    title: "Scarlet Sky",
    trans: "绯红色的天空",
    band: "Afterglow",
    season: "S2",
    ep: "第1话",
    type: "Insert",
  },
  {
    id: 208,
    title: "えがおのオーケストラっ！",
    trans: "笑容满溢的交响乐团！",
    band: "Hello, Happy World!",
    season: "S2",
    ep: "第1话",
    type: "Insert",
  },
  {
    id: 209,
    title: "LOUDER",
    trans: "高歌吧",
    band: "Roselia",
    season: "S2",
    ep: "第1话",
    type: "Insert",
  },
  {
    id: 210,
    title: "Happy Happy Party!",
    trans: "欢乐派对！",
    band: "Poppin'Party",
    season: "S2",
    ep: "第1–2、6话",
    type: "Insert",
  },
  {
    id: 211,
    title: "BLACK SHOUT",
    trans: "黑色咆哮",
    band: "Roselia",
    season: "S2",
    ep: "第2、12话",
    type: "Insert",
  },
  {
    id: 212,
    title: "キラキラだとか夢だとか ～Sing Girls～",
    trans: "无论闪耀还是梦想~歌之少女~",
    band: "Poppin'Party",
    season: "S2",
    ep: "第3话",
    type: "Insert",
  },
  {
    id: 213,
    title: "ゴーカ！ごーかい！？ファントムシーフ！",
    trans: "豪华!豪爽!?怪盗!",
    band: "Hello, Happy World!",
    season: "S2",
    ep: "第4话",
    type: "Insert",
  },
  {
    id: 214,
    title: "世界ノビノビ Treasure!",
    trans: "在世界不断延伸的宝藏!",
    band: "Hello, Happy World!",
    season: "S2",
    ep: "第4话",
    type: "Insert",
  },
  {
    id: 215,
    title: "パスパレボリューションず☆",
    trans: "Pasupare 大革命",
    band: "Pastel*Palettes",
    season: "S2",
    ep: "第5话",
    type: "Insert",
  },
  {
    id: 216,
    title: "ゆら・ゆらRing-Dong-Dance",
    trans: "摇・曳圆舞曲",
    band: "Pastel*Palettes",
    season: "S2",
    ep: "第5、11话",
    type: "Insert",
  },
  {
    id: 217,
    title: "That Is How I Roll! -instrumental-",
    trans: "这就是我的作风",
    band: "Afterglow",
    season: "S2",
    ep: "第6话（BGM）",
    type: "Insert",
  },
  {
    id: 218,
    title: "Y.O.L.O!!!!!",
    trans: "时光不再来",
    band: "Afterglow",
    season: "S2",
    ep: "第6话",
    type: "Insert",
  },
  {
    id: 219,
    title: "Don't be afraid!",
    trans: "别害怕！",
    band: "Glitter*Green",
    season: "S2",
    ep: "第7话",
    type: "Insert",
  },
  {
    id: 220,
    title: "泣かない泣かない",
    trans: "我不 哭我 不哭",
    band: "花园多惠 & LAYER",
    season: "S2",
    ep: "第7、10话",
    type: "Insert",
  },
  {
    id: 221,
    title: "ひとりじゃないんだから",
    trans: "因为并非孤单一人",
    band: "Pastel*Palettes",
    season: "S2",
    ep: "第8–9话",
    type: "Insert",
  },
  {
    id: 222,
    title: "Determination Symphony",
    trans: "决意交响曲",
    band: "Roselia",
    season: "S2",
    ep: "第9话",
    type: "Insert",
  },
  {
    id: 223,
    title: "UNSTOPPABLE",
    trans: "无法阻挡",
    band: "RAISE A SUILEN",
    season: "S2",
    ep: "第10话",
    type: "Insert",
  },
  {
    id: 224,
    title: "R・I・O・T",
    trans: "暴动",
    band: "RAISE A SUILEN",
    season: "S2",
    ep: "第10话",
    type: "Insert",
  },
  {
    id: 225,
    title: "きらきら星",
    trans: "小星星",
    band: "Poppin'Party",
    season: "S2",
    ep: "第11话",
    type: "Insert",
  },
  {
    id: 226,
    title: "STAR BEAT! ～ホシノコドウ～",
    trans: "STAR BEAT!～星之鼓动～",
    band: "Poppin'Party",
    season: "S2",
    ep: "第11话",
    type: "Insert",
  },
  {
    id: 227,
    title: "Returns",
    trans: "回归",
    band: "花园多惠",
    season: "S2",
    ep: "第11话",
    type: "Insert",
  },
  {
    id: 228,
    title: "Returns",
    trans: "回归",
    band: "Poppin'Party",
    season: "S2",
    ep: "第12–13话",
    type: "Insert",
  },
  {
    id: 229,
    title: "Dreamers Go!",
    trans: "追梦人 前进！",
    band: "户山香澄",
    season: "S2",
    ep: "第12话",
    type: "Insert",
  },
  {
    id: 230,
    title: "Dreamers Go!",
    trans: "追梦人 前进！",
    band: "Poppin'Party",
    season: "S2",
    ep: "第13话",
    type: "Insert",
  },
  {
    id: 231,
    title: "えがお・シング・あ・ソング",
    trans: "唱首欢笑的歌",
    band: "Hello, Happy World!",
    season: "S2",
    ep: "第13话",
    type: "Insert",
  },
  {
    id: 232,
    title: "きゅ～まい＊flower",
    trans: "可爱而坚强的花",
    band: "Pastel*Palettes",
    season: "S2",
    ep: "第13话",
    type: "Insert",
  },
  {
    id: 233,
    title: "ON YOUR MARK",
    trans: "各就各位",
    band: "Afterglow",
    season: "S2",
    ep: "第13话",
    type: "Insert",
  },
  {
    id: 234,
    title: "FIRE BIRD",
    trans: "火凤凰",
    band: "Roselia",
    season: "S2",
    ep: "第13话",
    type: "Insert",
  },
  // S3
  {
    id: 301,
    title: "イニシャル",
    trans: "Initial",
    band: "Poppin'Party",
    season: "S3",
    ep: "OP",
    type: "OP",
  },
  {
    id: 302,
    title: "夢を撃ち抜く瞬間に！",
    trans: "击穿梦想的瞬间！",
    band: "Poppin'Party",
    season: "S3",
    ep: "第1–6、8–12话",
    type: "ED",
  },
  {
    id: 303,
    title: "FIRE BIRD",
    trans: "火凤凰",
    band: "Roselia",
    season: "S3",
    ep: "第7话",
    type: "ED",
  },
  {
    id: 304,
    title: "Determination Symphony",
    trans: "决意交响曲",
    band: "Roselia",
    season: "S3",
    ep: "第1话",
    type: "Insert",
  },
  {
    id: 305,
    title: "R・I・O・T",
    trans: "暴动",
    band: "RAISE A SUILEN",
    season: "S3",
    ep: "第1–3、10话",
    type: "Insert",
  },
  {
    id: 306,
    title: "FIRE BIRD",
    trans: "火凤凰",
    band: "Roselia",
    season: "S3",
    ep: "第3话",
    type: "Insert",
  },
  {
    id: 307,
    title: "Step×Step!",
    trans: "一步一步",
    band: "Poppin'Party",
    season: "S3",
    ep: "第3–4话",
    type: "Insert",
  },
  {
    id: 308,
    title: "EXPOSE 'Burn out!!!'",
    trans: "燃尽曝光",
    band: "RAISE A SUILEN",
    season: "S3",
    ep: "第4–7、10话",
    type: "Insert",
  },
  {
    id: 309,
    title: "もういちど ルミナス",
    trans: "再次 闪耀",
    band: "Pastel*Palettes",
    season: "S3",
    ep: "第5话",
    type: "Insert",
  },
  {
    id: 310,
    title: "ぽっぴん'しゃっふる",
    trans: "Poppin' Shuffle",
    band: "Poppin'Party",
    season: "S3",
    ep: "第5、9、13话",
    type: "Insert",
  },
  {
    id: 311,
    title: "LOUDER",
    trans: "高歌吧",
    band: "Roselia",
    season: "S3",
    ep: "第6–7话",
    type: "Insert",
  },
  {
    id: 312,
    title: "UNSTOPPABLE",
    trans: "无法阻挡",
    band: "RAISE A SUILEN",
    season: "S3",
    ep: "第6话",
    type: "Insert",
  },
  {
    id: 313,
    title: "しゅわりん☆どり～みん",
    trans: "气泡飞舞☆如梦幻",
    band: "Pastel*Palettes",
    season: "S3",
    ep: "第8话",
    type: "Insert",
  },
  {
    id: 314,
    title: "えがお・シング・あ・ソング",
    trans: "唱首欢笑的歌",
    band: "Hello, Happy World!",
    season: "S3",
    ep: "第9话",
    type: "Insert",
  },
  {
    id: 315,
    title: "Don't be afraid!",
    trans: "别害怕！",
    band: "Glitter*Green",
    season: "S3",
    ep: "第9话",
    type: "Insert",
  },
  {
    id: 316,
    title: "Dreamers Go!",
    trans: "追梦人 前进！",
    band: "Poppin'Party",
    season: "S3",
    ep: "第9话",
    type: "Insert",
  },
  {
    id: 317,
    title: "Beautiful Birthday",
    trans: "美好的生日",
    band: "RAISE A SUILEN",
    season: "S3",
    ep: "第11、13话",
    type: "Insert",
  },
  {
    id: 318,
    title: "ミライトレイン",
    trans: "驶向未来的列车",
    band: "Poppin'Party",
    season: "S3",
    ep: "第13话",
    type: "Insert",
  },
  {
    id: 319,
    title: "Avant-garde HISTORY",
    trans: "前卫派历史",
    band: "Roselia",
    season: "S3",
    ep: "第13话",
    type: "Insert",
  },
  {
    id: 320,
    title: "夢を撃ち抜く瞬間に！",
    trans: "击穿梦想的瞬间！",
    band: "Poppin'Party × Roselia × RAISE A SUILEN",
    season: "S3",
    ep: "第13话",
    type: "Insert",
  },
  // Film Live
  {
    id: 604,
    title: "ときめきエクスペリエンス！",
    trans: "心跳体验，Instrumental / Opening",
    band: "Poppin'Party",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "OP",
  },
  {
    id: 605,
    title: "二重の虹",
    trans: "二重之虹（Full 新增）",
    band: "Poppin'Party",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 606,
    title: "Happy Happy Party!",
    trans: "欢乐派对！",
    band: "Poppin'Party",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 607,
    title: "Y.O.L.O!!!!!",
    trans: "时光不再来",
    band: "Afterglow",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 608,
    title: "Scarlet Sky",
    trans: "绯红色的天空",
    band: "Afterglow",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 609,
    title: "ON YOUR MARK",
    trans: "各就各位，Full",
    band: "Afterglow",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 610,
    title: "しゅわりん☆どり～みん",
    trans: "气泡飞舞☆如梦幻",
    band: "Pastel*Palettes",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 611,
    title: "ゆら・ゆらRing-Dong-Dance",
    trans: "摇・曳圆舞曲",
    band: "Pastel*Palettes",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 612,
    title: "きゅ～まい＊flower",
    trans: "可爱而坚强的花，Full",
    band: "Pastel*Palettes",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 613,
    title: "えがおのオーケストラっ！",
    trans: "笑容满溢的交响乐团！",
    band: "Hello, Happy World!",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 614,
    title: "世界ノビノビ Treasure!",
    trans: "在世界不断延伸的宝藏!",
    band: "Hello, Happy World!",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 615,
    title: "えがお・シング・あ・ソング",
    trans: "唱首欢笑的歌，Full",
    band: "Hello, Happy World!",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 616,
    title: "LOUDER",
    trans: "高歌吧",
    band: "Roselia",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 617,
    title: "BLACK SHOUT",
    trans: "黑色咆哮",
    band: "Roselia",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 618,
    title: "FIRE BIRD",
    trans: "火凤凰，Full",
    band: "Roselia",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 619,
    title: "Returns",
    trans: "回归",
    band: "Poppin'Party",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 620,
    title: "Dreamers Go!",
    trans: "追梦人 前进！",
    band: "Poppin'Party",
    season: "Film Live",
    ep: "FILM LIVE",
    type: "Insert",
  },
  {
    id: 621,
    title: "BRAVE JEWEL",
    trans: "勇气宝石",
    band: "Roselia",
    season: "Film Live",
    ep: "FILM LIVE Encore（Full）",
    type: "Insert",
  },
  {
    id: 622,
    title: "キズナミュージック♪",
    trans: "友谊的华丽乐章♪",
    band: "Poppin'Party",
    season: "Film Live",
    ep: "FILM LIVE Encore（Full）",
    type: "Insert",
  },
  {
    id: 623,
    title: "Jumpin'",
    trans: "跃动吧！",
    band: "Poppin'Party",
    season: "Film Live",
    ep: "FILM LIVE End Credits",
    type: "ED",
  },
  {
    id: 601,
    title: "絆色のアンサンブル",
    trans: "羁绊色的合奏",
    band: "Poppin'Party × Pastel*Palettes × Morfonica",
    season: "Film Live",
    ep: "FILM LIVE 2nd Stage",
    type: "Insert",
  },
  {
    id: 602,
    title: "競宴Red×Violet",
    trans: "竞演 Red×Violet",
    band: "Roselia × Afterglow",
    season: "Film Live",
    ep: "FILM LIVE 2nd Stage",
    type: "Insert",
  },
  {
    id: 603,
    title: "RASHAPEOPLE!",
    trans: "RASHAPEOPLE!",
    band: "RAISE A SUILEN × Hello, Happy World!",
    season: "Film Live",
    ep: "FILM LIVE 2nd Stage",
    type: "Insert",
  },
  // Episode of Roselia
  {
    id: 801,
    title: "Proud of oneself",
    trans: "Proud of oneself",
    band: "Roselia",
    season: "Episode of Roselia",
    ep: "I（OP）",
    type: "OP",
  },
  {
    id: 802,
    title: "overtuRe",
    trans: "overtuRe",
    band: "Roselia",
    season: "Episode of Roselia",
    ep: "I（ED）",
    type: "ED",
  },
  {
    id: 803,
    title: "雨上がりの夢",
    trans: "雨后之梦",
    band: "凑友希那",
    season: "Episode of Roselia",
    ep: "I（插入曲）",
    type: "Insert",
  },
  {
    id: 804,
    title: "BLACK SHOUT",
    trans: "黑色咆哮",
    band: "Roselia",
    season: "Episode of Roselia",
    ep: "I（插入曲）",
    type: "Insert",
  },
  {
    id: 805,
    title: "Re:birth day",
    trans: "Re:birth day",
    band: "Roselia",
    season: "Episode of Roselia",
    ep: "I（插入曲）",
    type: "Insert",
  },
  {
    id: 806,
    title: "しゅわりん☆どり～みん",
    trans: "气泡飞舞☆如梦幻",
    band: "Pastel*Palettes",
    season: "Episode of Roselia",
    ep: "I（插入曲）",
    type: "Insert",
  },
  {
    id: 807,
    title: "LOUDER",
    trans: "高歌吧",
    band: "Roselia",
    season: "Episode of Roselia",
    ep: "I（插入曲）",
    type: "Insert",
  },
  {
    id: 808,
    title: "Happy Happy Party!",
    trans: "欢乐派对！",
    band: "Poppin'Party",
    season: "Episode of Roselia",
    ep: "I（插入曲）",
    type: "Insert",
  },
  {
    id: 809,
    title: "Neo-Aspect",
    trans: "Neo-Aspect",
    band: "Roselia",
    season: "Episode of Roselia",
    ep: "I（插入曲）",
    type: "Insert",
  },
  {
    id: 810,
    title: "約束",
    trans: "约定",
    band: "凑友希那",
    season: "Episode of Roselia",
    ep: "I（插入曲）",
    type: "Insert",
  },
  {
    id: 821,
    title: "Sing Alive",
    trans: "Sing Alive",
    band: "Roselia",
    season: "Episode of Roselia",
    ep: "II（OP）",
    type: "OP",
  },
  {
    id: 822,
    title: 'Singing "OURS"',
    trans: 'Singing "OURS"',
    band: "Roselia",
    season: "Episode of Roselia",
    ep: "II（ED）",
    type: "ED",
  },
  {
    id: 823,
    title: "約束",
    trans: "约定",
    band: "Roselia",
    season: "Episode of Roselia",
    ep: "II（插入曲）",
    type: "Insert",
  },
  {
    id: 824,
    title: '"UNIONS" Road',
    trans: '"UNIONS" Road',
    band: "Roselia",
    season: "Episode of Roselia",
    ep: "II（插入曲）",
    type: "Insert",
  },
  {
    id: 825,
    title: "LOUDER",
    trans: "高歌吧",
    band: "Roselia",
    season: "Episode of Roselia",
    ep: "II（插入曲）",
    type: "Insert",
  },
  {
    id: 826,
    title: "Ringing Bloom",
    trans: "Ringing Bloom",
    band: "Roselia",
    season: "Episode of Roselia",
    ep: "II（插入曲）",
    type: "Insert",
  },
  {
    id: 827,
    title: "きゅ～まい＊flower",
    trans: "可爱而坚强的花",
    band: "Pastel*Palettes",
    season: "Episode of Roselia",
    ep: "II（插入曲）",
    type: "Insert",
  },
  {
    id: 828,
    title: "Neo-Aspect",
    trans: "Neo-Aspect",
    band: "Roselia",
    season: "Episode of Roselia",
    ep: "II（插入曲）",
    type: "Insert",
  },
  {
    id: 829,
    title: "Song I am.",
    trans: "Song I am.",
    band: "Roselia",
    season: "Episode of Roselia",
    ep: "II（插入曲）",
    type: "Insert",
  },
  // Morfonication
  {
    id: 701,
    title: "flame of hope -instrumental-",
    trans: "希望之焰",
    band: "Morfonica",
    season: "Morfonication",
    ep: "前篇（ED）",
    type: "ED",
  },
  {
    id: 702,
    title: "寄る辺のSunny, Sunny",
    trans: "有所依靠的Sunny,Sunny",
    band: "Morfonica",
    season: "Morfonication",
    ep: "后篇（插入曲）",
    type: "Insert",
  },
  {
    id: 703,
    title: "fly with the night",
    trans: "fly with the night",
    band: "Morfonica",
    season: "Morfonication",
    ep: "前篇（插入曲）",
    type: "Insert",
  },
  // Poppin'Dream!
  {
    id: 901,
    title: "ぽっぴん'どりーむ！",
    trans: "Poppin' Dream!",
    band: "Poppin'Party",
    season: "Poppin'Dream!",
    ep: "OP",
    type: "OP",
  },
  {
    id: 902,
    title: "星の約束",
    trans: "星之约定",
    band: "Poppin'Party",
    season: "Poppin'Dream!",
    ep: "ED",
    type: "ED",
  },
  {
    id: 903,
    title: "天下トーイツ A to Z☆",
    trans: "天下トーイツ A to Z☆",
    band: "Pastel*Palettes",
    season: "Poppin'Dream!",
    ep: "插入曲",
    type: "Insert",
  },
  {
    id: 904,
    title: "走り始めたばかりのキミに ～Popipa Acoustic Ver.～",
    trans: "致刚刚起跑的你",
    band: "Poppin'Party",
    season: "Poppin'Dream!",
    ep: "插入曲",
    type: "Insert",
  },
  {
    id: 905,
    title: "金色へのプレリュード",
    trans: "通往金色的序曲",
    band: "Morfonica",
    season: "Poppin'Dream!",
    ep: "插入曲",
    type: "Insert",
  },
  {
    id: 906,
    title: "!NVADE SHOW!",
    trans: "!NVADE SHOW!",
    band: "RAISE A SUILEN",
    season: "Poppin'Dream!",
    ep: "插入曲",
    type: "Insert",
  },
  {
    id: 907,
    title: "DRIVE US CRAZY",
    trans: "DRIVE US CRAZY",
    band: "RAISE A SUILEN",
    season: "Poppin'Dream!",
    ep: "插入曲",
    type: "Insert",
  },
  {
    id: 908,
    title: "Breakthrough!",
    trans: "Breakthrough!",
    band: "Poppin'Party",
    season: "Poppin'Dream!",
    ep: "插入曲",
    type: "Insert",
  },
  {
    id: 909,
    title: "Time Lapse",
    trans: "Time Lapse",
    band: "Poppin'Party",
    season: "Poppin'Dream!",
    ep: "插入曲",
    type: "Insert",
  },
  {
    id: 910,
    title: "ときめきエクスペリエンス！",
    trans: "心跳体验！",
    band: "Poppin'Party",
    season: "Poppin'Dream!",
    ep: "插入曲",
    type: "Insert",
  },
  // CiRCLE THANKS PARTY!
  {
    id: 951,
    title: "CiRCLING",
    trans: "CiRCLING",
    band: "Poppin'Party",
    season: "CiRCLE THANKS PARTY!",
    ep: "ED 第1话",
    type: "ED",
  },
  {
    id: 952,
    title: "SAKURA MEMORIES",
    trans: "樱之记忆",
    band: "Poppin'Party",
    season: "CiRCLE THANKS PARTY!",
    ep: "ED 第2话",
    type: "ED",
  },
  {
    id: 953,
    title: "Photograph",
    trans: "照片",
    band: "Poppin'Party",
    season: "CiRCLE THANKS PARTY!",
    ep: "第1话",
    type: "Insert",
  },
  {
    id: 954,
    title: "しゅわりん☆どり～みん",
    trans: "气泡飞舞☆如梦幻",
    band: "Pastel*Palettes",
    season: "CiRCLE THANKS PARTY!",
    ep: "第2话",
    type: "Insert",
  },
  {
    id: 955,
    title: "CiRCLE THANKS MUSiC♪",
    trans: "CiRCLE THANKS MUSiC♪",
    band: "CiRCLE THANKS PARTY! 合唱",
    season: "CiRCLE THANKS PARTY!",
    ep: "第2话",
    type: "Insert",
  },
  // MyGO!!!!!
  {
    id: 401,
    title: "壱雫空",
    trans: "壱雫空",
    band: "MyGO!!!!!",
    season: "MyGO!!!!!",
    ep: "OP",
    type: "OP",
  },
  {
    id: 402,
    title: "栞",
    trans: "栞",
    band: "MyGO!!!!!",
    season: "MyGO!!!!!",
    ep: "ED",
    type: "ED",
  },
  {
    id: 403,
    title: "Here, the world!",
    trans: "Here, the world!",
    band: "sumimi",
    season: "MyGO!!!!!",
    ep: "第1、4、5、6、7话",
    type: "Insert",
  },
  {
    id: 404,
    title: "Sasanqua",
    trans: "茶梅",
    band: "Afterglow",
    season: "MyGO!!!!!",
    ep: "第1、12话",
    type: "Insert",
  },
  {
    id: 405,
    title: "Sprechchor",
    trans: "齐诵",
    band: "Roselia",
    season: "MyGO!!!!!",
    ep: "第1话",
    type: "Insert",
  },
  {
    id: 406,
    title: "しゅわりん☆どり～みん",
    trans: "气泡飞舞☆如梦幻",
    band: "Pastel*Palettes",
    season: "MyGO!!!!!",
    ep: "第3话",
    type: "Insert",
  },
  {
    id: 407,
    title: "もういちど ルミナス",
    trans: "再次 闪耀",
    band: "Pastel*Palettes",
    season: "MyGO!!!!!",
    ep: "第3话",
    type: "Insert",
  },
  {
    id: 408,
    title: "人間になりたいうた",
    trans: "想要成为人类之歌",
    band: "CRYCHIC",
    season: "MyGO!!!!!",
    ep: "第3话",
    type: "Insert",
  },
  {
    id: 409,
    title: "春日影",
    trans: "春日影",
    band: "CRYCHIC",
    season: "MyGO!!!!!",
    ep: "第3话",
    type: "Insert",
  },
  {
    id: 410,
    title: "碧天伴走",
    trans: "碧天伴走",
    band: "MyGO!!!!!",
    season: "MyGO!!!!!",
    ep: "第7话",
    type: "Insert",
  },
  {
    id: 411,
    title: "春日影",
    trans: "春日影",
    band: "MyGO!!!!!",
    season: "MyGO!!!!!",
    ep: "第7话",
    type: "Insert",
  },
  {
    id: 412,
    title: "詩超絆",
    trans: "詩超絆",
    band: "MyGO!!!!!",
    season: "MyGO!!!!!",
    ep: "第10话",
    type: "Insert",
  },
  {
    id: 413,
    title: "迷星叫",
    trans: "迷星叫",
    band: "MyGO!!!!!",
    season: "MyGO!!!!!",
    ep: "第12话",
    type: "Insert",
  },
  {
    id: 414,
    title: "迷路日々",
    trans: "迷路日々",
    band: "MyGO!!!!!",
    season: "MyGO!!!!!",
    ep: "第12话",
    type: "Insert",
  },
  {
    id: 415,
    title: "Ave Mujica",
    trans: "Ave Mujica",
    band: "Ave Mujica",
    season: "MyGO!!!!!",
    ep: "第13话",
    type: "Insert",
  },
  // MyGO!!!!! 剧场版
  {
    id: 451,
    title: "過惰幻",
    trans: "過惰幻",
    band: "MyGO!!!!!",
    season: "MyGO!!!!!",
    ep: "Movie前篇（ED）",
    type: "ED",
  },
  {
    id: 452,
    title: "歩拾道",
    trans: "歩拾道",
    band: "MyGO!!!!!",
    season: "MyGO!!!!!",
    ep: "Movie后篇（ED）",
    type: "ED",
  },
  {
    id: 453,
    title: "処救生",
    trans: "処救生",
    band: "MyGO!!!!!",
    season: "MyGO!!!!!",
    ep: "Movie后篇（FILM LIVE 插段）",
    type: "Insert",
  },
  {
    id: 454,
    title: "音一会",
    trans: "音一会",
    band: "MyGO!!!!!",
    season: "MyGO!!!!!",
    ep: "Movie后篇（FILM LIVE 插段）",
    type: "Insert",
  },
  {
    id: 455,
    title: "壱雫空",
    trans: "壱雫空",
    band: "MyGO!!!!!",
    season: "MyGO!!!!!",
    ep: "Movie后篇（FILM LIVE 插段）",
    type: "Insert",
  },
  // Ave Mujica
  {
    id: 501,
    title: "KiLLKiSS",
    trans: "KiLLKiSS",
    band: "Ave Mujica",
    season: "Ave Mujica",
    ep: "第1话以完整版插曲替代OP；第9话额外用作插曲；第12话用作ED",
    type: "OP",
  },
  {
    id: 502,
    title: "Georgette Me, Georgette You",
    trans: "Georgette Me, Georgette You",
    band: "Ave Mujica",
    season: "Ave Mujica",
    ep: "第12话用作OP（第1、10、13话未使用）",
    type: "ED",
  },
  {
    id: 503,
    title: "金色へのプレリュード",
    trans: "通往金色的序曲",
    band: "Morfonica",
    season: "Ave Mujica",
    ep: "第1话",
    type: "Insert",
  },
  {
    id: 504,
    title: "Ave Mujica",
    trans: "Ave Mujica",
    band: "Ave Mujica",
    season: "Ave Mujica",
    ep: "第2、5、9话",
    type: "Insert",
  },
  {
    id: 505,
    title: "Here, the world!",
    trans: "此刻，世界",
    band: "sumimi",
    season: "Ave Mujica",
    ep: "第5、11话",
    type: "Insert",
  },
  {
    id: 506,
    title: "迷路日々",
    trans: "迷路日々",
    band: "MyGO!!!!!",
    season: "Ave Mujica",
    ep: "第7话",
    type: "Insert",
  },
  {
    id: 507,
    title: "人間になりたいうたⅡ",
    trans: "想要成为人类之歌Ⅱ",
    band: "CRYCHIC",
    season: "Ave Mujica",
    ep: "第7话",
    type: "Insert",
  },
  {
    id: 508,
    title: "春日影",
    trans: "春日影",
    band: "CRYCHIC",
    season: "Ave Mujica",
    ep: "第7话",
    type: "Insert",
  },
  {
    id: 509,
    title: "もういちど ルミナス",
    trans: "再次 闪耀",
    band: "Pastel*Palettes",
    season: "Ave Mujica",
    ep: "第8话",
    type: "Insert",
  },
  {
    id: 510,
    title: "Imprisoned XII",
    trans: "Imprisoned XII",
    band: "Ave Mujica",
    season: "Ave Mujica",
    ep: "第10话",
    type: "Insert",
  },
  {
    id: 511,
    title: "Crucifix X",
    trans: "Crucifix X",
    band: "Ave Mujica",
    season: "Ave Mujica",
    ep: "第10话",
    type: "Insert",
  },
  {
    id: 513,
    title: "聿日箋秋",
    trans: "聿日箋秋",
    band: "MyGO!!!!!",
    season: "Ave Mujica",
    ep: "第13话",
    type: "Insert",
  },
  {
    id: 514,
    title: "焚音打",
    trans: "焚音打",
    band: "MyGO!!!!!",
    season: "Ave Mujica",
    ep: "第13话",
    type: "Insert",
  },
  {
    id: 515,
    title: "八芒星ダンス",
    trans: "八芒星Dance",
    band: "Ave Mujica",
    season: "Ave Mujica",
    ep: "第13话",
    type: "Insert",
  },
  {
    id: 516,
    title: "顔",
    trans: "顔",
    band: "Ave Mujica",
    season: "Ave Mujica",
    ep: "第13话",
    type: "Insert",
  },
  {
    id: 517,
    title: "天球のMúsica",
    trans: "天球的Musica",
    band: "Ave Mujica",
    season: "Ave Mujica",
    ep: "第13话",
    type: "Insert",
  },
];

// ============================================================
// 乐队图片映射
// ============================================================
const bandImages = {
  "Glitter*Green": "images/GlitterGreen.png",
  CHiSPA: "images/CHiSPA.png",
  "Poppin'Party": "images/Popipa.png",
  Roselia: "images/Roselia.png",
  Afterglow: "images/Afterglow.png",
  "Pastel*Palettes": "images/Pasupare.png",
  "Hello, Happy World!": "images/Hhw.png",
  "RAISE A SUILEN": "images/RAS.png",
  Morfonica: "images/Morfonica.png",
  "MyGO!!!!!": "images/MyGO.png",
  "Ave Mujica": "images/Ave_Mujica.png",
  CRYCHIC: "images/CRYCHIC.png",
  sumimi: "images/sumimi.png",
};

// Hero 区域背景图
const heroImageUrl = "images/Background.svg";

// ============================================================
// 乐队标签 CSS 类名映射
// ============================================================
const bandStyles = {
  "Poppin'Party": "band-tag-PoppinParty",
  Roselia: "band-tag-Roselia",
  Afterglow: "band-tag-Afterglow",
  "Pastel*Palettes": "band-tag-PastelPalettes",
  "Hello, Happy World!": "band-tag-HelloHappyWorld",
  "RAISE A SUILEN": "band-tag-RAISEASUILEN",
  Morfonica: "band-tag-Morfonica",
  "MyGO!!!!!": "band-tag-MyGO",
  "Ave Mujica": "band-tag-AveMujica",
  "Glitter*Green": "band-tag-GlitterGreen",
  CHiSPA: "band-tag-CHiSPA",
  CRYCHIC: "band-tag-CRYCHIC",
  sumimi: "band-tag-sumimi",
};

// ============================================================
// 筛选选项
// ============================================================
const seasons = [
  "全部",
  "S1",
  "S2",
  "S3",
  "Film Live",
  "Episode of Roselia",
  "Morfonication",
  "Poppin'Dream!",
  "CiRCLE THANKS PARTY!",
  "MyGO!!!!!",
  "Ave Mujica",
];

const bands = [
  "全部",
  "Poppin'Party",
  "Roselia",
  "RAISE A SUILEN",
  "MyGO!!!!!",
  "Ave Mujica",
  "Morfonica",
  "Afterglow",
  "Pastel*Palettes",
  "Hello, Happy World!",
  "其他",
];

// ============================================================
// 常量
// ============================================================

/** localStorage 中收藏数据的存储键 */
const FAV_KEY = "bangdream_favs";

/** 主要乐队集合（"其他"筛选时取反集） */
const MAIN_BANDS = new Set([
  "Poppin'Party",
  "Roselia",
  "RAISE A SUILEN",
  "MyGO!!!!!",
  "Ave Mujica",
  "Morfonica",
  "Afterglow",
  "Pastel*Palettes",
  "Hello, Happy World!",
]);
